name: Build
# This workflow runs periodically builds (daily) to deploy the
# CometBFT documentation website to Netlify
on:
  push:
    branches:
      - andy/deploy-build
jobs:
  build:
    name: Build Jekyll site and Deploy to Netlify
    runs-on: ubuntu-latest
    container:
      image: jekyll/builder:stable
      env:
        JEKYLL_UID: 1001
        JEKYLL_GID: 1001
    steps:
      # Build the Jekyll website
      - name: Checkout site
        uses: actions/checkout@v3
      # Clone the cometbft repo
      - name: Clone cometbft repo
        uses: actions/checkout@v3
        with:
          repository: cometbft/cometbft
          path: build
      # Install Jekyll dependencies
      - name: Install dependencies
        run: |
          bundle install
      # Build the Jekyll website
      - name: Build website
        run: |
          chmod a+wx .
          bundle exec jekyll build --disable-disk-cache -V
      # Deploy the _site folder to Netlify CometBFT documentation website
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: './_site'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5